Develop
SmartCity-2022/Service-Jobportal pull request #27
Opened 2022-06-21 22:23 UTC by cv7l1

Closes #24 
  * Reiter "meine Bewerbungen" funktioniert jetzt
Closes #25
  * Bewerbungen können reviewed werden

2022-06-21 22:28 UTC, fwatermann requested changes

2022-06-21 22:28 UTC, fwatermann commented on backend/routes/api/applications.js
> +    return res.json({status: 400, message: "file is not in pdf format"}).status(400)
Für ungültiges Format sollte mit `415 Unsupported Media Type` geantwortet werden.

2022-06-21 22:28 UTC, fwatermann commented on backend/routes/api/applications.js
> +      return res.json({status: 200, message: "application does not exist"}).status(200)
Nicht gefunden = `404 Not found`

2022-06-22 00:09 UTC, Flamtky commented
@cv7l1 ist das richtig das es ein major Update ist (bzw. der finale Release, wo alles funktioniert und alles größtenteils fehlerfrei ist)?

2022-06-22 00:43 UTC, cv7l1 commented
@Flamtky Alle Priorisierten Features (User Stories) sind implementiert, ab jetzt kommt nur noch Refactoring/Bug Fixes/kleinere Änderungen

2022-06-22 02:49 UTC, Flamtky commented
> kleinere Änderungen

Ich ändere vorerst mal auf minor, wir klären das sonst im Meeting mit den Final Release (v1)

2022-06-22 12:08 UTC, fwatermann approved these changes

2022-06-22 12:34 UTC, merged